### ISSUE TITLE
clearify backend protocol for BOMs and non ASCII-7-bit characters

### ISSUE THREAD

**Issue by mthiede** [mthiede/rtext#1]
BOM bytes should not count for the column index and BOM bytes shouldn't be sent in the context lines.

Each escaped non ASCII-7-bit character (byte) should probably count as 1 independently of the actual encoding (count the bytes)

Update the Protocol description

**Comment by hbragge** [comment]
Just wanted to add that currently loading the model from a file with BOM leads to an exception:

Model loaded (0.005994921s)
[12:52:06] DEBUG response: {"type"=>"response", "invocation_id"=>11, "problems"=>[], "total_problems"=>0}
[12:52:06] INFO request complete (0.442189841s)
/home/henri/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/json/common.rb:155:in `parse': 757: unexpected token at '{"context":["���AUTOSAR {","  ARPackage P1 {","    "],"column":5,"type":"request","command":"content_complete","invocation_id":1' (JSON::ParserError)
	from /home/henri/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/json/common.rb:155:in `parse'
	from /home/henri/.rvm/rubies/ruby-2.1.7/lib/ruby/2.1.0/json/common.rb:468:in `JSON'
	from /home/henri/work/bcdevo/priv/rtext/lib/rtext/json_interface.rb:25:in `json_to_object'
	from /home/henri/work/bcdevo/priv/rtext/lib/rtext/message_helper.rb:32:in `extract_message'
	from /home/henri/work/bcdevo/priv/rtext/lib/rtext/service.rb:78:in `block in run'
	from /home/henri/work/bcdevo/priv/rtext/lib/rtext/service.rb:58:in `each'
	from /home/henri/work/bcdevo/priv/rtext/lib/rtext/service.rb:58:in `run'
	from /home/henri/work/bcdevo/priv/automate/lib/esr/automate/automate-rtext-service.rb:120:in `<top (required)>'
	from /home/henri/.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/henri/.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/henri/work/bcdevo/priv/automate-test/../automate/automate-rtext-service.rb:2:in `<main>'
